import Loading from "@/app/loading";
import { QueryProvider } from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Oxanium } from "next/font/google";
import { Suspense } from "react";
import "react-big-calendar/lib/addons/dragAndDrop/styles.css";
import "react-big-calendar/lib/css/react-big-calendar.css";
import { Toaster } from "sonner";
import "./globals.css";

const font = Oxanium({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Noze",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading />}>
        <body
          className={cn("dark:bg-[#0f0f10] bg-white overflow-x-hidden", font.className)}
        >
          <QueryProvider>
            <Toaster position="bottom-left" richColors />
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          </QueryProvider>
        </body>
      </Suspense>
    </html>
  );
}
